GET http://localhost:3000
###


GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John",
    "password": "12345"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "John",
    "password": "12345"
}